apiVersion: v1
stringData:
  rootHost: "%"
  rootPassword: "root"
  rootUser: "root"
kind: Secret
metadata:
  name: mypwds
  namespace: mysql-operator
type: Opaque
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
  namespace: mysql-operator
spec:
  imagePullPolicy: IfNotPresent
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 1
  router:
    instances: 1
