apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-hydra-admin
  namespace: open-hydra

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-hydra-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: open-hydra-admin
  namespace: open-hydra

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-hydra-kube-system
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: open-hydra-admin
  namespace: open-hydra

---

apiVersion: v1
data:
  config.yaml: |
    podAllocatableLimit: -1
    defaultCpuPerDevice: 2000
    defaultRamPerDevice: 8192
    defaultGpuPerDevice: 0
    datasetBasePath: /mnt/public-dataset
    datasetVolumeType: hostpath
    jupyterLabHostBaseDir: /mnt/jupyter-lab
    imageRepo: "registry.cn-shanghai.aliyuncs.com/openhydra/jupyter:Python-3.8.18-dual-lan"
    vscodeImageRepo: "registry.cn-shanghai.aliyuncs.com/openhydra/vscode:1.85.1"
    defaultGpuDriver: nvidia.com/gpu
    serverIP: "localhost"
    patchResourceNotRelease: true
    disableAuth: true
    mysqlConfig:
      address: mycluster-instances.mysql-operator.svc
      port: 3306
      username: root
      password: openhydra
      databaseName: openhydra
      protocol: tcp
    leaderElection:
      leaderElect: false
      leaseDuration: 30s
      renewDeadline: 15s
      retryPeriod: 5s
      resourceLock: endpointsleases
      resourceName: open-hydra-api-leader-lock
      resourceNamespace: default
    authDelegateConfig:
      keystoneConfig:
        endpoint: http://keystone.openhydra.svc:5000
        username: admin
        password: admin
        domainId: default
kind: ConfigMap
metadata:
  name: open-hydra-config
  namespace: open-hydra

---

# deployment that mount configmap open-hydra-config to /etc/open-hydra/config.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-hydra-server
  namespace: open-hydra
  labels:
    app: open-hydra-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-hydra-api
  template:
    metadata:
      labels:
        app: open-hydra-api
    spec:
      serviceAccountName: open-hydra-admin
      containers:
      - name: open-hydra-api
        image: registry.cn-shanghai.aliyuncs.com/openhydra/open-hydra-server:latest
        imagePullPolicy: IfNotPresent
        command: ["open-hydra-server", "run","--open-hydra-server-config", "/etc/open-hydra/config.yaml"]
        ports:
        - containerPort: 443
        securityContext:
          privileged: true
        volumeMounts:
        - name: open-hydra-config
          mountPath: /etc/open-hydra/config.yaml
          subPath: config.yaml
        - name: dataset
          mountPath: /mnt/public-dataset
          mountPropagation: Bidirectional
        - name: course
          mountPath: /mnt/public-course
          mountPropagation: Bidirectional
      volumes:
      - name: open-hydra-config
        configMap:
          name: open-hydra-config
          items:
          - key: config.yaml
            path: config.yaml
      - name: dataset
        hostPath:
          # This will mount the "/mnt/data" directory from the host node to the "/etc/nginx/conf.d" path in the container.
          path: /mnt/public-dataset
          type: Directory
      - name: course
        hostPath:
          # This will mount the "/mnt/data" directory from the host node to the "/etc/nginx/conf.d" path in the container.
          path: /mnt/public-course
          type: Directory


---

apiVersion: v1
kind: Service
metadata:
  name: open-hydra-server
  namespace: open-hydra
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
  selector:
    app: open-hydra-api
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.open-hydra-server.openhydra.io
spec:
  group: open-hydra-server.openhydra.io
  groupPriorityMinimum: 1000
  insecureSkipTLSVerify: true
  service:
    name: open-hydra-server
    namespace: open-hydra
    port: 443
  version: v1
  versionPriority: 15

---

apiVersion: v1
data:
  sandbox: |
    {
        "sandboxes": {
            "jupyter-lab": {
                "cpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/jupyter:Python-3.8.18-dual-lan",
                "gpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/jupyter:Python-3.8.18-dual-lan",
                "command": [],
                "description": "jupyter lab 是在线的 python 开发环境",
                "developmentInfo": [
                    "python-version: 3.8",
                    "jupyter-lab-version: 4.0.9",
                    "torch-version: 1.8.1+cu111",
                    "cuda-version: 11.1",
                    "lan: chinese | english"
                ]
            },
            "vscode": {
                "cpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/vscode:1.85.1",
                "gpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/vscode:1.85.1",
                "command": [],
                "description": "vscode 是在线的代码编辑器,并可以自行编辑代码和安装各种开发环境",
                "developmentInfo": [
                    "vscode-version: 1.85.1"
                ]
            },
            "keras": {
                "cpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/tensorflow:latest-gpu-with-jlab",
                "gpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/tensorflow:latest-gpu-with-jlab",
                "command": [],
                "description": "keras 是在线的深度学习开发环境",
                "developmentInfo": [
                    "keras-version: 2.6.1",
                    "tensorflow-version: 2.6.0",
                    "jupyter-lab-version: 4.0.9",
                    "lan: chinese | english"
                ]
            },
            "PaddlePaddle": {
                "cpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/paddle:2.6.0-jlab",
                "gpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/paddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6-jlab",
                "command": [],
                "description": "PaddlePaddle 是在线的深度学习开发环境",
                "developmentInfo": [
                    "PaddlePaddle-version: 2.1.0",
                    "jupyter-lab-version: 4.0.9",
                    "cuda-version: 12.0",
                    "lan: chinese | english"
                ]
            }
        }
    }
kind: ConfigMap
metadata:
  name: openhydra-sandbox
  namespace: open-hydra
