name: Sync To Gitee
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SECRET }}
        with:
          source-repo: "https://github.com/openhydra/open-hydra.git"
          destination-repo: "https://gitee.com/sephiroth/open-hydra.git"
